In [1]:
squareArray = [
            [".", ".", ".", ".", ".", ".", ".", "."],
            [".", ".", ".", ".", ".", ".", ".", "."],
            [".", ".", ".", ".", ".", ".", ".", "."],
            [".", ".", ".", "q", ".", ".", ".", "."],
            ["q", ".", ".", ".", "q", ".", ".", "."],
            [".", "q", ".", ".", ".", "q", ".", "q"],
            [".", ".", "q", ".", ".", ".", "q", "."],
            [".", ".", ".", ".", ".", ".", ".", "."],
            ]

In [2]:
attackCounts = 0
queenList = []
for r in range(0,8):
    for c in range(0,8):
        if squareArray[r][c] == "q":
            queenList.append( ( r,c ) )

In [3]:
row, col = zip(*queenList)

In [4]:
row

(3, 4, 4, 5, 5, 5, 6, 6)

In [5]:
col

(3, 0, 4, 1, 5, 7, 2, 6)

In [6]:
## number of queens in the same row
rowList = list(row)
rowSet = set(rowList)
attackRow = len(rowList) - len(list(rowSet))

In [7]:
attackRow

4

In [8]:
rowList

[3, 4, 4, 5, 5, 5, 6, 6]

In [9]:
rowSet

{3, 4, 5, 6}

In [15]:
colList = list(col)
attackDiag = 0
for i in range(0,7):
    for j in range(i+1,8):
        if abs(rowList[j] - rowList[i]) == abs(colList[j] - colList[i]):
            attackDiag = attackDiag + 1

In [16]:
attackDiag

12

In [18]:
attackRow = 0
for i in range(0,7):
    for j in range(i+1,8):
        if rowList[j] == rowList[i]:
            attackRow = attackRow + 1

In [19]:
attackRow

5

In [85]:
%run solveEightQueens.py -l

iteration  0
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . q . . . . 
q . . . q . . . 
. q . . . q . q 
. . q . . . q . 
. . . . . . . . 
# attacks: 17
18 12 14 13 13 12 14 14 
14 16 13 15 12 14 12 16 
14 12 18 13 15 12 14 14 
15 14 14 q 13 16 13 16 
q 14 17 15 q 14 16 16 
17 q 16 18 15 q 15 q 
18 14 q 15 15 14 q 16 
14 14 13 17 12 14 12 18 
# attacks: 17
iteration  1
. . . . . . . . 
. . . . . . . . 
. q . . . . . . 
. . . q . . . . 
q . . . q . . . 
. . . . . q . q 
. . q . . . q . 
. . . . . . . . 
# attacks: 12
14 12 10 10 8 8 8 10 
11 16 10 11 7 9 7 12 
11 q 15 10 10 9 10 11 
12 14 11 q 8 12 8 12 
q 14 12 12 q 10 11 12 
12 17 11 13 10 q 9 q 
13 14 q 11 10 11 q 12 
10 14 9 12 7 10 8 14 
# attacks: 12
iteration  2
. . . . . . . . 
. . . . . . . . 
. q . . . . . . 
. . . q . . . . 
q . . . . . . . 
. . . . . q . q 
. . q . . . q . 
. . . . q . . . 
# attacks: 7
9 7 6 6 8 4 4 5 
7 10 6 7 7 5 3 6 
7 q 10 6 10 5 5 6 
9 9 7 q 8 7 4 7 
q 9 7 7 12 5 6 7 
8 12 8 8 10 q 6 q 
9 9 q

In [25]:
%run autograder.py --mute

Starting on 3-13 at 17:35:26

Question q1

*** PASS: test_cases/q1/graph_backtrack.test
*** 	solution:		['1:A->C', '0:C->G']
*** 	expanded_states:	['A', 'D', 'C']
*** PASS: test_cases/q1/graph_bfs_vs_dfs.test
*** 	solution:		['2:A->D', '0:D->G']
*** 	expanded_states:	['A', 'D']
*** PASS: test_cases/q1/graph_infinite.test
*** 	solution:		['0:A->B', '1:B->C', '1:C->G']
*** 	expanded_states:	['A', 'B', 'C']
*** PASS: test_cases/q1/graph_manypaths.test
*** 	solution:		['2:A->B2', '0:B2->C', '0:C->D', '2:D->E2', '0:E2->F', '0:F->G']
*** 	expanded_states:	['A', 'B2', 'C', 'D', 'E2', 'F']
*** PASS: test_cases/q1/pacman_1.test
*** 	pacman layout:		mediumMaze
*** 	solution length: 130
*** 	nodes expanded:		146

### Question q1: 2/2 ###


Question q2

*** PASS: test_cases/q2/graph_backtrack.test
*** 	solution:		['1:A->C', '0:C->G']
*** 	expanded_states:	['A', 'B', 'C', 'D']
*** PASS: test_cases/q2/graph_bfs_vs_dfs.test
*** 	solution:		['1:A->G']
*** 	expanded_states:	['A', 'B']
*** PASS: test_ca

In [26]:
n = [1,2,3,4,5]
n.index(min(n))

0

In [5]:
n = [[2,1,'q',4],[2,3,0,4]]

In [12]:
import numpy as np

In [70]:
import random

In [74]:
random.randint(0,8)

2

In [7]:
int('q')

ValueError: invalid literal for int() with base 10: 'q'

In [18]:
a = np.sort([2,0,1,'q',3])

In [19]:
a[0]

'0'

In [28]:
a = [[2,3],[5,6]]

In [30]:
b = np.reshape(a,(1,4))

In [31]:
b

array([[2, 3, 5, 6]])

In [36]:
c = [1,2,3,'q']

In [37]:
min(c)

1

In [38]:
d = [[0,2,1,'q'],[2,3,5,'q']]

In [50]:
np.where(d == 1)

(array([], dtype=int64),)

In [48]:
np.asarray(d)

array([['0', '2', '1', 'q'],
       ['2', '3', '5', 'q']], 
      dtype='|S21')

In [51]:
a = ([[1 1 0 0],
  [0 0 1 1],
  [0 0 0 0]])

SyntaxError: invalid syntax (<ipython-input-51-845e57851a73>, line 1)

In [52]:
a = [2,3]

In [53]:
np.where(a == 2)

(array([], dtype=int64),)

In [56]:
a.index(2)

0

In [57]:
a = [[2,3],[2,3]]

In [58]:
a.index(2)

ValueError: 2 is not in list